export const geolocationHomeLabelsDatabase = [
    {"account_number":"644935064","name":"Wesley Flynn","agg_risk":"Low","geolocation_list":"United States(3)","home_location_list":"MD, US(3)"},
    {"account_number":"596577485","name":"Vincent Salem","agg_risk":"Low","geolocation_list":"United States(4)","home_location_list":"FL, US(4)"},
    {"account_number":"789292686","name":"Adrian Adalia","agg_risk":"Low","geolocation_list":"United States(3)","home_location_list":"FL, US(3)"},
    {"account_number":"229144115","name":"Henry Eden","agg_risk":"Low","geolocation_list":"Ghana(1), United States(4)","home_location_list":"MA, US(5)"},
    {"account_number":"5558280","name":"Declan Ezra","agg_risk":"Low","geolocation_list":"United States(1258)","home_location_list":"FL, US(1258)"},
    {"account_number":"145107291","name":"Hudson Aero","agg_risk":"Low","geolocation_list":"United States(6)","home_location_list":"GA, US(6)"},
    {"account_number":"5551248","name":"Finn River","agg_risk":"Low","geolocation_list":"(1)","home_location_list":"NC, US(1)"},
    {"account_number":"452445594","name":"Oscar Hunter","agg_risk":"Low","geolocation_list":"United States(5)","home_location_list":"NY, US(5)"},
    {"account_number":"269820177","name":"Caleb Indigo","agg_risk":"Low","geolocation_list":"United States(4)","home_location_list":"MD, US(4)"},
    {"account_number":"5551211","name":"Asher Kai","agg_risk":"Low","geolocation_list":"(2)","home_location_list":"NC, US(2)"},
    {"account_number":"958266453","name":"Benjamin Charlie","agg_risk":"Low","geolocation_list":"Ghana(1), United States(6)","home_location_list":"VA, US(7)"},
    {"account_number":"452231594","name":"Connor Fallon","agg_risk":"Low","geolocation_list":"United States(6)","home_location_list":"CA, US(6)"},
    {"account_number":"450841883","name":"Gabriel Riley","agg_risk":"Low","geolocation_list":"Vietnam(1), Ghana(1), United States(1)","home_location_list":"CT, US(3)"},
    {"account_number":"967843599","name":"Soren Parker","agg_risk":"Low","geolocation_list":"United States(1)","home_location_list":"NY, US(1)"},
    {"account_number":"140365900","name":"Jacob Cameron","agg_risk":"Low","geolocation_list":"United States(7)","home_location_list":"FL, US(7)"},
    {"account_number":"397578766","name":"Gideon Ember","agg_risk":"Low","geolocation_list":"United States(5)","home_location_list":"MA, US(5)"},
    {"account_number":"718445993","name":"Sebastian Briar","agg_risk":"Low","geolocation_list":"United States(6), Mauritius(1), Ghana(2)","home_location_list":"MN, US(9)"},
    {"account_number":"925286284","name":"Arlo Skye","agg_risk":"Low","geolocation_list":"United States(1)","home_location_list":"CO, US(1)"},
    {"account_number":"476180291","name":"Isaac Aubrey","agg_risk":"Low","geolocation_list":"Ghana(1), United States(4)","home_location_list":"RI, US(5)"},
    {"account_number":"784784082","name":"Nolan Carter","agg_risk":"Low","geolocation_list":"United States(3)","home_location_list":"MD, US(3)"},
    {"account_number":"389164666","name":"Arlo Skye","agg_risk":"Low","geolocation_list":"United States(7)","home_location_list":"SC, US(7)"},
    {"account_number":"763881080","name":"Beau Lennox","agg_risk":"Low","geolocation_list":"United States(1)","home_location_list":"IN, US(1)"},
    {"account_number":"121686539","name":"Tobias Ashton","agg_risk":"Low","geolocation_list":"United States(1)","home_location_list":"IN, US(1)"},
    {"account_number":"427770229","name":"Thomas Robin","agg_risk":"Low","geolocation_list":"United States(18)","home_location_list":"CT, US(18)"},
    {"account_number":"493082132","name":"Wyatt Skylar","agg_risk":"Low","geolocation_list":"United States(15)","home_location_list":"MA, US(15)"},
    {"account_number":"775790404","name":"Gavin Bodhi","agg_risk":"Low","geolocation_list":"United States(1)","home_location_list":"NY, US(1)"},
    {"account_number":"850106954","name":"Xander Morgan","agg_risk":"Low","geolocation_list":"United States(3)","home_location_list":"SC, US(3)"},
    {"account_number":"8675309","name":"Omnibus International","agg_risk":"Low","geolocation_list":"Spain(1), Switzerland(21), Hrvatska(5), Deutschland(2), Nederland(1), Cyprus(15)","home_location_list":"PA, US(45)"},
    {"account_number":"699575145","name":"Archer Aspen","agg_risk":"Low","geolocation_list":"Algeria(1), United States(10)","home_location_list":"CO, US(11)"},
    {"account_number":"218519669","name":"Arthur Elliot","agg_risk":"Low","geolocation_list":"United Arab Emirates(1), United States(10)","home_location_list":"TX, US(11)"},
    {"account_number":"728040042","name":"Lincoln Shiloh","agg_risk":"Low","geolocation_list":"United States(2)","home_location_list":"NJ, US(2)"},
    {"account_number":"232882270","name":"Callum Jude","agg_risk":"Low","geolocation_list":"United States(11)","home_location_list":"NJ, US(11)"},
    {"account_number":"362181272","name":"Nathaniel Jordan","agg_risk":"Low","geolocation_list":"United States(4)","home_location_list":"FL, US(4)"},
    {"account_number":"199609531","name":"Grayson Sawyer","agg_risk":"Low","geolocation_list":"Philippines(1), United States(35)","home_location_list":"IL, US(36)"},
    {"account_number":"540616908","name":"Kaden Oakley","agg_risk":"Low","geolocation_list":"United States(2)","home_location_list":"FL, US(2)"},
    {"account_number":"508153448","name":"Isaac Aubrey","agg_risk":"Low","geolocation_list":"United States(11), Ghana(3)","home_location_list":"GA, US(14)"},
    {"account_number":"824514243","name":"Axel Blair","agg_risk":"Low","geolocation_list":"United States(5)","home_location_list":"WI, US(5)"},
    {"account_number":"898046447","name":"William Dylan","agg_risk":"Low","geolocation_list":"Ghana(1), United States(18)","home_location_list":"NC, US(19)"},
    {"account_number":"222337876","name":"Noah Julian","agg_risk":"Low","geolocation_list":"United States(9)","home_location_list":"NY, US(9)"},
    {"account_number":"328686723","name":"Theo Bailey","agg_risk":"Low","geolocation_list":"United States(23)","home_location_list":"VA, US(23)"},
    {"account_number":"681454191","name":"Milo Addison","agg_risk":"Low","geolocation_list":"United States(8), South Africa(1)","home_location_list":"MI, US(9)"},
    {"account_number":"834727576","name":"Dominic Spencer","agg_risk":"Low","geolocation_list":"United States(13)","home_location_list":"FL, US(13)"},
    {"account_number":"717751544","name":"Elliott Rain","agg_risk":"Low","geolocation_list":"United States(8)","home_location_list":"MA, US(8)"},
    {"account_number":"55563257","name":"Jasper James","agg_risk":"Low","geolocation_list":"United States(44), (24)","home_location_list":"WV, US(68)"},
    {"account_number":"367548780","name":"Emmett Hayden","agg_risk":"Low","geolocation_list":"United States(24), Ghana(2)","home_location_list":"NC, US(26)"},
    {"account_number":"409342555","name":"Levi Darcy","agg_risk":"Low","geolocation_list":"United States(6), Ghana(2)","home_location_list":"FL, US(8)"},
    {"account_number":"547494176","name":"Atlas Piper","agg_risk":"Low","geolocation_list":"United States(9)","home_location_list":"WA, US(9)"},
    {"account_number":"5557101","name":"Oliver Willow","agg_risk":"Low","geolocation_list":"United States(116)","home_location_list":"CT, US(116)"},
    {"account_number":"55565248","name":"Silas Quinn","agg_risk":"Low","geolocation_list":"United States(2)","home_location_list":"PA, US(2)"},
    {"account_number":"170659913","name":"Rhys Bennett","agg_risk":"Low","geolocation_list":"United States(7)","home_location_list":"MD, US(7)"},
    {"account_number":"587463471","name":"Ronan Poppy","agg_risk":"Low","geolocation_list":"United States(3)","home_location_list":"NJ, US(3)"},
    {"account_number":"5556547","name":"Theodore Rowan","agg_risk":"Low","geolocation_list":"United States(732)","home_location_list":"SC, US(732)"},
    {"account_number":"5552185","name":"Owen Avery","agg_risk":"Low","geolocation_list":"United States(1)","home_location_list":"OH, US(1)"},
    {"account_number":"346586644","name":"Simon Hadley","agg_risk":"Low","geolocation_list":"United States(4)","home_location_list":"KY, US(4)"},
    {"account_number":"161549806","name":"Alastair Arden","agg_risk":"Low","geolocation_list":"United States(5)","home_location_list":"NC, US(5)"},
    {"account_number":"605463799","name":"Ace Austin","agg_risk":"Low","geolocation_list":"United States(3)","home_location_list":"TN, US(3)"},
    {"account_number":"581392937","name":"Leo Jade","agg_risk":"Low","geolocation_list":"United States(8), Bulgaria(1)","home_location_list":"IN, US(9)"},
    {"account_number":"415540534","name":"Aaron Ellis","agg_risk":"Low","geolocation_list":"United States(2)","home_location_list":"IL, US(2)"},
    {"account_number":"688860118","name":"Elias Echo","agg_risk":"Low","geolocation_list":"United States(4)","home_location_list":"UT, US(4)"},
    {"account_number":"155198872","name":"Miles Everly","agg_risk":"Low","geolocation_list":"United States(17)","home_location_list":"CT, US(17)"},
    {"account_number":"731335846","name":"Andrew Harlow","agg_risk":"Low","geolocation_list":"United States(3)","home_location_list":"LA, US(3)"},
    {"account_number":"257476634","name":"Jack Orion","agg_risk":"Low","geolocation_list":"Ghana(1), United States(5)","home_location_list":"GA, US(6)"},
    {"account_number":"55522445","name":"Felix Harper","agg_risk":"Low","geolocation_list":"United States(2)","home_location_list":"IL, US(2)"},
    {"account_number":"5554415","name":"Ethan Luca","agg_risk":"Low","geolocation_list":"United States(1)","home_location_list":"NC, US(1)"},
    {"account_number":"376603253","name":"Atticus Ryan","agg_risk":"Low","geolocation_list":"Ghana(1), United States(3)","home_location_list":"OH, US(4)"},
    {"account_number":"55584568","name":"Alexander Sage","agg_risk":"Low","geolocation_list":"United States(1)","home_location_list":"MD, US(1)"},
    {"account_number":"663894110","name":"Atticus Ryan","agg_risk":"Low","geolocation_list":"United States(5)","home_location_list":"VA, US(5)"},
    {"account_number":"612666295","name":"August Finley","agg_risk":"Low","geolocation_list":"Ghana(1), United States(3)","home_location_list":"FL, US(4)"},
    {"account_number":"434333482","name":"Atlas Piper","agg_risk":"Low","geolocation_list":"United States(2), China(1)","home_location_list":"RI, US(3)"},
    {"account_number":"737122530","name":"Lucas Raven","agg_risk":"Low","geolocation_list":"United States(25)","home_location_list":"IA, US(25)"},
    {"account_number":"107721414","name":"Samuel Blake","agg_risk":"Low","geolocation_list":"Mauritius(1), United States(7)","home_location_list":"FL, US(8)"},
    {"account_number":"640955550","name":"Noah Julian","agg_risk":"Low","geolocation_list":"United States(12), Ghana(1)","home_location_list":"NY, US(13)"},
    {"account_number":"613918435","name":"Landon Beckett","agg_risk":"Low","geolocation_list":"United States(10)","home_location_list":"NJ, US(10)"},
    {"account_number":"673958079","name":"Eli Emerson","agg_risk":"Low","geolocation_list":"United States(5)","home_location_list":"MI, US(5)"},
    {"account_number":"903682288","name":"Grayson Sawyer","agg_risk":"Low","geolocation_list":"United States(11)","home_location_list":"TX, US(11)"},
    {"account_number":"603848743","name":"Miles Everly","agg_risk":"Low","geolocation_list":"United States(11)","home_location_list":"NY, US(11)"},
    {"account_number":"55521234","name":"Liam Logan","agg_risk":"Low","geolocation_list":"United States(2)","home_location_list":"WI, US(2)"},
    {"account_number":"542905759","name":"Elijah Artemis","agg_risk":"Low","geolocation_list":"United States(5), Ghana(1)","home_location_list":"NJ, US(6)"},
    {"account_number":"980034637","name":"Jackson Zephyr","agg_risk":"Low","geolocation_list":"United States(11)","home_location_list":"TN, US(11)"},
    {"account_number":"935784525","name":"Aiden Rory","agg_risk":"Low","geolocation_list":"United States(6)","home_location_list":"MD, US(6)"},
    {"account_number":"659950142","name":"Max Phoenix","agg_risk":"Low","geolocation_list":"United States(2)","home_location_list":"FL, US(2)"},
    {"account_number":"510011367","name":"Everett Nova","agg_risk":"Low","geolocation_list":"Mauritius(1), United States(2), Ghana(1)","home_location_list":"NJ, US(4)"},
];