export const sample = [
    {
        name: 'Oliver Willow',
        accountnumber: "231553453",
        ipaddress: ['9.9.9.9', '8.8.8.8"'],
        riskLevel: 'high',
        ipcoord: ["123,456","1,2"],
        addresscoord: "123,456",
        startdate: new Date(),
        enddate: new Date(),
        ipcountry: ["Ghana(10)", "Yemen(5)"],
        customercountry: 'USA',
        address: '123 main street',
        reason: 'reason'
    },
    {
        name: 'Oliver Willow',
        accountnumber: "231553453",
        ipaddress: '9.9.9.9',
        riskLevel: 'high',
        ipcoordlat: 123,
        ipcoordlng: 456,
        addresscoordlat: 123,
        addresscoordlng:456,
        startdate: new Date(),
        enddate: new Date(),
        ipcountry: 'Canada',
        customercountry: 'Brazil',
        address: '123 main street'
    },
    {
        name: 'Oliver Willow',
        accountnumber: "231553453",
        ipaddress: '9.9.9.9',
        riskLevel: 'high',
        ipcoordlat: 123,
        ipcoordlng: 456,
        addresscoordlat: 123,
        addresscoordlng:456,
        startdate: new Date(),
        enddate: new Date(),
        ipcountry: 'Canada',
        customercountry: 'Brazil',
        address: '123 main street'
    },
];